name: Generate Data Model
on:
  push:
    branches:
      - main

jobs:
  common-deploy-cloud-run:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      MODEL: "gpt-4-turbo"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script
        run: ./generate_data_model_graph.sh

      - name: Create new branch and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          BRANCH_NAME="update-data-model-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $BRANCH_NAME
          git add diagram.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update data model graph"
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: $BRANCH_NAME
          title: "🔄 Auto-update data model graph"
          body: "This PR updates the data model graph with the latest changes."
          base: main

