name: Generate Data Model
on:
  push:
    branches:
      - main

jobs:
  generate-data-model:
    permissions:
      contents: write  # Permission pour push
      id-token: write
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      MODEL: "gpt-4-turbo"

    outputs:
      branch_name: ${{ steps.branch-name.outputs.branch }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run script
        run: ./generate_data_model_graph.sh

      - name: Generate branch name
        id: branch-name
        run: echo "branch=update-data-model-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT

      - name: Create new branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git checkout -b ${{ steps.branch-name.outputs.branch }}
          echo "🛠 Nouvelle branche créée : ${{ steps.branch-name.outputs.branch }}"

      - name: Check for changes and commit
        run: |
          git checkout ${{ steps.branch-name.outputs.branch }}
          git add diagram.json
          
          # Vérifie s'il y a des changements
          if git diff --cached --quiet; then
            echo "✅ Aucun changement détecté, pas de commit nécessaire."
            exit 0  # On arrête le job proprement
          fi

          # S'il y a des changements, commit et push
          git commit -m "🔄 Auto-update data model graph"
          git push origin ${{ steps.branch-name.outputs.branch }}
          echo "✅ Commit et push effectués sur ${{ steps.branch-name.outputs.branch }}"

  create-pull-request:
    needs: generate-data-model  # Attend que le job précédent finisse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ needs.generate-data-model.outputs.branch_name }}
          title: "🔄 Auto-update data model graph"
          body: "This PR updates the data model graph with the latest changes."
          base: main


