name: Generate Data Model
on:
  push:
    branches:
      - main

jobs:
  common-deploy-cloud-run:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      MODEL: "gpt-4-turbo"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script
        run: ./generate_data_model_graph.sh

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add diagram.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update data model graph"
          git push || echo "No changes to push"
          

