name: (Meal Plan Service) Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'meal-plan-service/**'

jobs:
  ci-codecov:
    uses: ./.github/workflows/common-ci.yml
    with:
      gcp_project_id: "dhomotic"
      gcp_app_name: "meal-plan-service"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  deploy:
    needs: ci-codecov
    uses: ./.github/workflows/common-deploy-cloud-run.yml
    with:
      environment: prod
      image_tag: 0.0.${{ github.run_number }}
      gcp_project_id: "dhomotic"
      gcp_app_name: "meal-plan-service"
      cloud_run_region: "europe-west1"
      env_vars_string: "NODE_ENV=production"  # uniquement les variables non sensibles
      cloud_run_service_account: "api-meal-plan-service@dhomotic.iam.gserviceaccount.com"
    secrets:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      ENV_VAR_API_KEY: ${{ secrets.API_KEY }}
