name: (Meal Plan Service) Continuous Integration
on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/common-ci.yml
    with:
      gcp_project_id: "dhomotic"
      gcp_app_name: "meal-plan-service"
